######################################################################
# Automatically generated by qmake (3.0) Fri Feb 8 11:26:29 2013
######################################################################

TEMPLATE = app
TARGET = ex-union
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
