######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 24 13:47:20 2010
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += main.cpp

