#! /bin/sh

rm -rf build
for compiler in gcc clang; do
  for cpp in cpp14 cpp17 cpp20 cpp23; do
     echo "========= $compiler - $cpp ==========="
     cmake --preset $cpp-$compiler .
     cd build/$cpp-$compiler
     ninja || exit 1
     cd ../..
  done
done

for compiler in gcc clang; do
  for cpp in cpp14 cpp17 cpp20 cpp23; do
    echo "\n\n========= $compiler - $cpp ==========="
    cd build/$cpp-$compiler
    ./tst_kdalgorithms -silent

    if [ ! $? -eq 0 ]; then
      echo "\n\n\n FAILURE \n\n\n"
      exit 1
    fi

    cd ../..
  done
done
